apiVersion: v1
kind: Service
metadata:
  name: image-caption-generator-app-2
  labels:
    app: image-caption-generator-app-2
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: image-caption-generator-app-2